//
//  APIMethodCall.swift
//  APIMethodCall
//
//  Created by Stephen Kockentiedt on 16.09.21.
//

import Foundation

/// Protocol used by API method calls generated by SwiftyBridges
public protocol APIMethodCall: Encodable {
    associatedtype ReturnType: Decodable
    
    /// The name of the API this Call is part of
    static var typeName: String { get }
    
    /// The ID of the method this type represents
    static var methodID: String { get }
}

/// This is used as a replacement for the `Void` return type in generated code to prevent compiler errors because `Void` does not conform to `Codable`
public struct NoReturnValue: Codable {
    public init() {}
    public init(from decoder: Decoder) throws {}
    public func encode(to encoder: Encoder) throws {}
}
