import Foundation

/// Marks a struct that was generated by SwiftyBridges used to represent a Fluent model on the server.
public protocol FluentModelStruct: Codable {
    associatedtype IDValue: Codable, Hashable
    var id: IDValue? { get }
}

extension Optional: FluentModelStruct where Wrapped: FluentModelStruct {
    public var id: Wrapped.IDValue?? {
        self.map { $0.id }
    }
}
